nb/config/routes.rb
Rails.application.routes.draw do
  resources :presidents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

nb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

nb/app/models/president.rb
class President < ApplicationRecord
end

nb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

nb/app/controllers/presidents_controller.rb
class PresidentsController < ApplicationController
  before_action :set_president, only: %i[ show edit update destroy ]

  # GET /presidents or /presidents.json
  def index
    @presidents = President.all
  end

  # GET /presidents/1 or /presidents/1.json
  def show
  end

  # GET /presidents/new
  def new
    @president = President.new
  end

  # GET /presidents/1/edit
  def edit
  end

  # POST /presidents or /presidents.json
  def create
    @president = President.new(president_params)

    respond_to do |format|
      if @president.save
        format.html { redirect_to president_url(@president), notice: "President was successfully created." }
        format.json { render :show, status: :created, location: @president }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @president.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presidents/1 or /presidents/1.json
  def update
    respond_to do |format|
      if @president.update(president_params)
        format.html { redirect_to president_url(@president), notice: "President was successfully updated." }
        format.json { render :show, status: :ok, location: @president }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @president.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presidents/1 or /presidents/1.json
  def destroy
    @president.destroy!

    respond_to do |format|
      format.html { redirect_to presidents_url, notice: "President was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_president
      @president = President.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def president_params
      params.require(:president).permit(:name, :comment, :image_url)
    end
end

nb/app/helpers/application_helper.rb
module ApplicationHelper
end

nb/app/helpers/presidents_helper.rb
module PresidentsHelper
end

nb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <style>
* {
   box-sizing: border-box;
}
.imageColumn {
   float: left;
   width: 25%;
   padding: 10px;
}
h1{
   text-align: center;
}
</style>
</head>
<body>
    
    <style>
body {
  background-image: url("http://146.111.120.96/SP23/ET_710_C3/NBaguaei06/Flag.jpeg");
  background-position: 50% 50%;
  background-repeat: repeat;
}
</style>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

nb/app/views/presidents/_form.html.erb
<%= form_with(model: president) do |form| %>
  <% if president.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(president.errors.count, "error") %> prohibited this president from being saved:</h2>

      <ul>
        <% president.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

nb/app/views/presidents/_president.html.erb
<div id="<%= dom_id president %>">
  <p>
    <strong>Name:</strong>
    <%= president.name %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= president.comment %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= president.image_url %>
  </p>
  
    <img src="<%= president.image_url %>" width="500" height="700" alt=""/>


</div>

nb/app/views/presidents/edit.html.erb
<h1>Editing president</h1>

<%= render "form", president: @president %>

<br>

<div>
  <%= link_to "Show this president", @president %> |
  <%= link_to "Back to presidents", presidents_path %>
</div>

nb/app/views/presidents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Term Project</h1>

<div class="alignRow">



<div id="presidents">
  <% @presidents.each do |president| %>
  <div class="imageColumn">

  <h3>
    <%= president.name %>
  </h3>

    <img src="<%= president.image_url %>" width="500" height="700" alt=""/>

    <p>
      <%= link_to president.name, president %>
    </p>
    </div>

  <% end %>
</div>

</div>

<%= link_to "New president", new_president_path %>

nb/app/views/presidents/new.html.erb
<h1>New president</h1>

<%= render "form", president: @president %>

<br>

<div>
  <%= link_to "Back to presidents", presidents_path %>
</div>

nb/app/views/presidents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @president %>

<div>
  <%= link_to "Edit this president", edit_president_path(@president) %> |
  <%= link_to "Back to presidents", presidents_path %>

  <%= button_to "Destroy this president", @president, method: :delete %>
</div>